In [1]:
import numpy as np

In [2]:
def will_it_work(meshes, currents, resistor_to_max_current):
    for mesh in meshes:
        for resis in mesh['resistors']:
            resistor_index = resis['resistor_idx']
            current_index = resis['current_index']
            current = abs(currents[current_index])
            if current > resistor_to_max_current[resistor_index]:
                return False
    return True

def calculate_powers(meshes, currents):
    powers = []
    for mesh in meshes:
        for resis in mesh['resistors']:
            current_index = resis['current_index']
            current = abs(currents[current_index])
            powers.append((current**2)*resis['value'])
    return powers

In [4]:
meshes = [
    {
        "resistors": [
            {"resistor_idx": 0, "value": 10.0, "current_index": 0},
            {"resistor_idx": 2, "value": 5.0, "current_index": 1},
        ]
    },
    {
        "resistors": [
            {"resistor_idx": 1, "value": 15.0, "current_index": 2},
        ]
    }
]

currents = [1.00, 1.2, 1.5]  # Токове в Ампери
resistor_to_max_current = [1.0, 1.5, 2.5]  # Максимално допустими токове

# Проверка дали веригата ще работи
is_safe = will_it_work(meshes, currents, resistor_to_max_current)
print("Веригата ще работи?" , "Да" if is_safe else "Не")

# Изчисляване на мощностите
powers = calculate_powers(meshes, currents)
print("Мощности на резисторите:", powers)

Веригата ще работи? Да
Мощности на резисторите: [10.0, 7.199999999999999, 33.75]


In [ ]:
import numpy as np

class ShortCircuitError(Exception):
    """Грешка, ако системата няма решение (сингулярна матрица)."""
    pass

def solve_for_currents(meshes):
    
    # Определяме броя на неизвестните токове
    num_currents = len({resistor["current_index"] for mesh in meshes for resistor in mesh["resistors"]})
    
    # Инициализиране на матрица на съпротивленията (A) и вектор на напреженията (B)
    resistance_matrix = np.zeros((num_currents, num_currents))  # Матрица A
    print(resistance_matrix)
    voltage_vector = np.zeros(num_currents)  # Вектор B
    
    # Построяване на системата
    for mesh in meshes:
        for resistor in mesh["resistors"]:
            current_idx = resistor["current_index"]  # Индекс на тока
            direction = resistor.get("direction", "positive")  # Посока на тока
            direction = 1 if direction == "positive" else -1
            resistance_matrix[mesh["mesh_id"], current_idx] += direction * resistor["value"]  # Добавяме съпротивление
        
        for voltage in mesh.get("voltages", []):
            direction = voltage.get("direction", "rising")  # Посока на напрежението
            direction = 1 if direction == "rising" else -1
            voltage_vector[mesh["mesh_id"]] += direction * voltage["value"]  # Добавяме напрежение
    
    # Решаване на системата A * X = B
    try:
        currents = np.linalg.solve(resistance_matrix, voltage_vector)  # Решаваме чрез numpy
        return currents.tolist()
    except np.linalg.LinAlgError:
        # Ако матрицата е сингулярна, хвърляме грешка
        raise ShortCircuitError("Системата няма решение. Възможно е късо съединение.")

solve_for_currents(meshes)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


KeyError: 'mesh_id'

In [11]:
import pandas as pd
meshes

[{'resistors': [{'resistor_idx': 0, 'value': 10.0, 'current_index': 0},
   {'resistor_idx': 2, 'value': 5.0, 'current_index': 1}]},
 {'resistors': [{'resistor_idx': 1, 'value': 15.0, 'current_index': 2}]}]

In [17]:
dict = {'az':'Valio','az':'misho'}

In [19]:
dicti = dict.get('az',22)

In [20]:
dicti

'misho'

In [21]:
operations = [
    {"operation": "create", "order_id": 4, "address": "ул. Раковски 25", "status": "pending"},
    {"operation": "update", "order_id": 2, "status": "completed"},
    {"operation": "check", "order_id": 1},
    {"operation": "check", "order_id": 4},
    {"operation": "update", "order_id": 5, "status": "in progress"}  # Опитай да обновиш несъществуваща поръчка
]
for oper in operations:
    print(oper['operation'])

create
update
check
check
update


In [22]:
def solve_for_currents(nodes,meshes):
    num_currents = len(nodes)
    resistance_matrix = np.zeros((num_currents, num_currents))
    voltage_vector = np.zeros(num_currents)
    for mesh in meshes:
        for resistor in mesh['resistors']:
            current_idx = resistor['current_index']
            direction = resistor.get('direction','positive')
            direction = 1 if direction == 'positive' else -1
            resistance_matrix[mesh['mesh_id'],current_idx] += direction * resistor['value']
        for voltage in mesh.get('voltages',[]):
            direction = voltage.get('direction','rising')
            direction = 1 if direction == 'rising' else -1
            voltage_vector[mesh['mesh_id']] += direction * voltage['value']
    try:
        currents = np.linalg.solve(resistance_matrix,voltage_vector)
        return currents.tolist()
    except np.linalg.LinAlgError:
        raise ShortCircuitError('Системата няма решение. Възможно е късо съединение.')


In [23]:
solve_for_currents(nodes,meshes)

NameError: name 'nodes' is not defined

In [24]:
nodes = { 
    "node_1": {"type": "source", "voltage": 10.0},
    "node_2": {"type": "source", "voltage": 5.0},
    "node_3": {"type": "sink"},
    "node_4": {"type": "sink"},
    "node_5": {"type": "sink"}
}

In [25]:
solve_for_currents(nodes,meshes)

KeyError: 'mesh_id'

In [26]:
rows = 5  # Брой редове
cols = 7  # Брой колони
reserved_seats = [
    {"row": 1, "col": 3},
    {"row": 2, "col": 5},
    {"row": 4, "col": 1},
    {"row": 5, "col": 7}
]


seats = np.zeros((rows,cols))

In [28]:
for seat in reserved_seats:
    seats[seat['row']-1,seat['col']-1] = 1

In [30]:
def check_seat(seats,row,col):
    if seats[row-1,col-1] == 0:
        return True
    return False

In [31]:
def free_seats(seats):
    free = 0
    for i in range(seats.shape[0]):
        for j in range(seats.shape[1]):
            if seats[i,j] == 0:
                free+=1
    return free

In [32]:
free_seats(seats)

31

In [33]:
def find_most_empty_row(seats):
    max_empty = 0
    row = 0
    for i in range(seats.shape[0]):
        empty = np.sum(seats[i] == 0)
        if empty > max_empty:
            max_empty = empty
            row = i
    return row

find_most_empty_row(seats)

2

In [34]:
seats

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
A =np.array ([
    [3, 5, 7],
    [2, 8, 1],
    [6, 4, 9]
])
sum = 0
T = A.max()
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        sum += A[i,j]
sum

AttributeError: 'numpy.int32' object has no attribute 'index'

In [42]:
A.transpose()

array([[3, 2, 6],
       [5, 8, 4],
       [7, 1, 9]])

In [45]:
meshes = [
{
"mesh_id": 0,
"resistors": [
{"resistor_idx": 0, "value": 10.0, "current_index": 0, "direction": "positive"},
{"resistor_idx": 1, "current_index": 4, "direction": "positive"},
{"resistor_idx": 2, "current_index": 2, "direction": "negative"}
],
"voltages": [
{"value": 12.0, "direction": "rising"},
{"value": 9.0, "direction": "dropping"}
],
},
# ...
]

for mesh in meshes:
    for resistor in mesh['resistors']:
        print(resistor['current_index'])

0
4
2


In [46]:
np.linalg.solve(np.array([[1,2],[3,4]]),np.array([5,6]))

array([-4. ,  4.5])

In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.matrix_rank(a)

2

In [53]:
import numpy as np

class ShortCircuitError(Exception):
    pass

def will_it_work(nodes, meshes, currents, resistor_to_max_current):
    for mesh in meshes:
        for resistor in mesh["resistors"]:
            resistor_idx = resistor["resistor_idx"]
            current_idx = resistor["current_index"]
            if abs(currents[current_idx]) > resistor_to_max_current[resistor_idx]:
                return False
    return True

def solve_for_currents(nodes, meshes):
    equations = []
    constants = []

    # Формулиране на уравненията от втория закон на Кирхоф
    for mesh in meshes:
        equation = np.zeros(len(meshes))
        voltage_sum = 0

        for resistor in mesh["resistors"]:
            current_idx = resistor["current_index"]
            value = resistor.get("value", 0)
            direction = 1 if resistor["direction"] == "positive" else -1
            equation[current_idx] += direction * value

        for voltage in mesh["voltages"]:
            direction = 1 if voltage["direction"] == "rising" else -1
            voltage_sum += direction * voltage["value"]

        equations.append(equation)
        constants.append(voltage_sum)

    # Решаване на системата от уравнения
    A = np.array(equations)
    b = np.array(constants)

    if np.linalg.matrix_rank(A) < len(A):
        raise ShortCircuitError("Няма решение за системата.")

    currents = np.linalg.lstsq(A, b, rcond=None)[0]
    return currents.tolist()

def calculate_powers(meshes, currents):
    powers = []

    for mesh in meshes:
        for resistor in mesh["resistors"]:
            resistor_idx = resistor["resistor_idx"]
            current_idx = resistor["current_index"]
            value = resistor.get("value", 0)

            power = currents[current_idx]**2 * value
            powers.append({"resistor_idx": resistor_idx, "power": power})

    return powers

# Примерни данни
nodes = [
    {
        "node_id": 0,
        "incoming_currents": [0],
        "outgoing_currents": [1, 2]
    }
]

meshes = [
    {
        "mesh_id": 0,
        "resistors": [
            {"resistor_idx": 0, "value": 10.0, "current_index": 0, "direction": "positive"},
            {"resistor_idx": 1, "value": 1.0, "current_index": 2, "direction": "positive"}
        ],
        "voltages": [
            {"voltage_idx": 0, "value": 9.0, "direction": "rising"}
        ],
    },
    {
        "mesh_id": 1,
        "resistors": [
            {"resistor_idx": 2, "value": 5.0, "current_index": 1, "direction": "positive"},
            {"resistor_idx": 1, "current_index": 2, "direction": "negative"}
        ],
        "voltages": [
            {"voltage_idx": 1, "value": 6.0, "direction": "rising"},
            {"voltage_idx": 2, "value": 1.0, "direction": "falling"}
        ],
    }
]

currents = [0.5, 0.3, 0.2]
resistor_to_max_current = [100, 50, 10]

# Тестове
try:
    print("Will it work?", will_it_work(nodes, meshes, currents, resistor_to_max_current))
    solved_currents = solve_for_currents(nodes, meshes)
    print("Solved currents:", solved_currents)
    powers = calculate_powers(meshes, solved_currents)
    print("Powers:", powers)
except ShortCircuitError as e:
    print("Error:", e)


Will it work? True


IndexError: index 2 is out of bounds for axis 0 with size 2