In [1]:

import numpy as np
nodes = [{
    'node_id': 0,
    'incoming_current': [0,1],
    'outgoing_current': [4]
},
]
meshes = [
{
"mesh_id": 0,
"resistors": [
{"resistor_idx": 0, "value": 10.0, "current_index": 0, "direction": "positive"},
{"resistor_idx": 1, "value": 9.0, "current_index": 4, "direction": "positive"},
{"resistor_idx": 2, "value": 11.0, "current_index": 2, "direction": "negative"}
],
"voltages": [
{"value": 12.0, "direction": "rising"},
{"value": 9.0, "direction": "dropping"}
],
},
]



In [2]:
def will_it_work(nodes, meshes, currents, resistor_to_max_current):
    for mesh in meshes:
        for resistor in mesh['resistors']:
            resistor_idx = resistor['resistor_idx']
            current_idx = resistor['current_index']
            if abs(currents[current_idx]) > resistor_to_max_current[resistor_idx]:
                return False
    return True

In [3]:

currents = [0.5, 11.3, 0.2, 0.1, 0.4] 
resistor_to_max_current = [1.0, 2.8, 1.2]

In [4]:
if will_it_work(nodes, meshes, currents, resistor_to_max_current):
    print("Веригата ще работи безопасно.")
else:
    print("Веригата ще изгори!")

Веригата ще работи безопасно.


In [5]:
A = np.array([
    [1, 0, -1, 0],   # Уравнение за въглерод (C)
    [0, 2, 0, -2],   # Уравнение за водород (H)
    [0, 0, 2, -1]    # Уравнение за кислород (O)
])

b = np.array([0, 0, 0])  

result = np.linalg.lstsq(A,b)
result

C:\Users\vyoto\AppData\Local\Temp\ipykernel_19052\2350061129.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  result = np.linalg.lstsq(A,b)


(array([0., 0., 0., 0.]),
 array([], dtype=float64),
 3,
 array([3.02044792, 2.23606798, 0.93642638]))

In [6]:
import numpy as np

A = np.array([
    [1, 0, -1, 0],   # Уравнение за въглерод (C)
    [0, 2, 0, -2],   # Уравнение за водород (H)
    [0, 0, 2, -1]    # Уравнение за кислород (O)
])

b = np.array([0, 0, 0])  # Дясната страна на уравнението

# Решение чрез np.linalg.lstsq
result = np.linalg.lstsq(A, b, rcond=None)

solution, residuals, rank, singular_values = result

# Показване на резултата
print("Решение (x):", solution)
print("Остатъчна грешка:", residuals)
print("Ранг на матрицата:", rank)
print("Сингуларни стойности:", singular_values)


Решение (x): [0. 0. 0. 0.]
Остатъчна грешка: []
Ранг на матрицата: 3
Сингуларни стойности: [3.02044792 2.23606798 0.93642638]


In [7]:
import numpy as np

# Разходи за пренос на енергия
costs = np.array([
    [5, 8, 6],
    [6, 4, 3],
    [3, 5, 7]
])


supply = np.array([50, 60, 70])

# Търсене в градовете
demand = np.array([40, 50, 90])

a = np.eye(4)

In [8]:
import numpy as np

# Матрица A (числата от 1 до 9)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Матрица B (матрица от нули с размер 3x2)
B = np.zeros((3, 2))

print("Матрица A:")
print(A)
print("\nМатрица B:")
print(B)

Матрица A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица B:
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
import numpy as np

# Матрица A и вектор B
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 18])

result,_,_,_ = np.linalg.lstsq(A,B,rcond=None)

In [10]:
result

array([1.2, 5.6])

In [11]:
import numpy as np

# Матрици A и B
A = np.array([[1, 2], [3, 4]])
B = np.zeros((2, 2))

# Построяване на блокова матрица C
C = np.vstack((np.hstack((A, B)), np.hstack((B, A))))
d = np.vstack((A,B))
print("Блокова матрица C:")
print(C)


Блокова матрица C:
[[1. 2. 0. 0.]
 [3. 4. 0. 0.]
 [0. 0. 1. 2.]
 [0. 0. 3. 4.]]


In [12]:

np.transpose(d)

array([[1., 3., 0., 0.],
       [2., 4., 0., 0.]])

In [13]:
d

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [0., 0.]])

In [14]:
def will_it_work(nodes, meshes, currents, resistor_to_max_current):
    """
    Проверява дали токовете през резисторите са в допустимите граници.
    """
    for mesh in meshes:
        for resistor in mesh['resistors']:
            resistor_idx = resistor['resistor_idx'] 
            current_idx = resistor['current_index'] 
            current_value = abs(currents[current_idx]) 
            
            # Проверка дали токът е по-голям от максималния допустим ток
            if current_value > resistor_to_max_current[resistor_idx]:
                return False  # Веригата ще изгори
    return True  # Веригата ще работи

In [15]:
# Примерни данни
meshes = [
    {
        "resistors": [
            {"resistor_idx": 0, "value": 10.0, "current_index": 0},
            {"resistor_idx": 1, "value": 5.0, "current_index": 1},
        ]
    },
    {
        "resistors": [
            {"resistor_idx": 2, "value": 15.0, "current_index": 2},
        ]
    }
]

currents = [0.5, 1.2, 2.0]
resistor_to_max_current = [0.0, 1.5, 2.5]  

# Проверка дали веригата ще работи
result = will_it_work(nodes, meshes, currents, resistor_to_max_current)
print("Веригата ще работи?" , "Да" if result else "Не")

Веригата ще работи? Не


In [16]:
-abs(abs(abs(abs(2))))

-2

In [17]:
def calculate_powers(meshes, currents):
    powers = []
    for mesh in meshes:
        for res in mesh['resistors']:
            res_idx = res['resistor_idx']
            cur_idx = res['current_index']
            current = abs(currents[cur_idx])
            powers.append(((current*current)*res['value']))
    return powers


In [18]:
meshes = [
    {
        "resistors": [
            {"resistor_idx": 0, "value": 10.0, "current_index": 0},
            {"resistor_idx": 1, "value": 5.0, "current_index": 1},
        ]
    },
    {
        "resistors": [
            {"resistor_idx": 2, "value": 15.0, "current_index": 2},
        ]
    }
]

# Примерни токове
currents = [0.5, 1.2, 2.0]  # Токове във веригата (в Ампери)

# Изчисляване на мощностите
powers = calculate_powers(meshes, currents)

# Извеждане на резултата
print("Мощности на резисторите:", powers)

Мощности на резисторите: [2.5, 7.199999999999999, 60.0]


In [27]:
a = np.array(([2,3],[1,4]))
b = np.array(([1,2],[3,1]))
c = np.array(([7,5],[6,8]))
ab = np.add(a,b)
mult = np.matmul(a,b)
if np.linalg.det(a) != 0:
    result = np.linalg.inv(a)
result2 = np.matmul(a,result)
result2

array([[1., 0.],
       [0., 1.]])

In [30]:
import numpy as np

# Създаваме празна матрица с нули
matrix = np.zeros((3, 4))

# Попълваме матрицата със стойности i + j
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        matrix[i, j] = i + j

print("Попълнена матрица:")
print(matrix)

Попълнена матрица:
[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]


In [36]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Комбинираме хоризонтално
combined = np.hstack((A, B))
print("Комбинирана матрица (хоризонтално):")
print(combined)

# Извличаме първия ред
first_row = combined[0,:]
print("Първи ред:", first_row)

Комбинирана матрица (хоризонтално):
[[1 2 5 6]
 [3 4 7 8]]
Първи ред: [1 2 5 6]


In [37]:
import numpy as np

# Матрица на коефициентите
A = np.array([[1, 1], [1, -1]])

# Вектор на резултатите
b = np.array([6, 2])

# Решаване чрез метода на най-малките квадрати
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Решение (x1, x2):", x)

Решение (x1, x2): [4. 2.]


In [41]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[1,2,3]])
print(M.shape[0])

4


In [43]:
result = 33

def random(a):
    a = a+2
    return result
random(5)

33

In [7]:
for i in range(0,10,5):

    if i == 5:
        break
    print(i)

0
